### ISSUE TITLE
Support for private networks

### ISSUE THREAD

**Issue by codekoala** [kahkhang/kube-linode#11]
This is a lower-priority item for me, personally, but it would be great if this supported private networking to avoid possible bandwidth charges.

**Comment by kahkhang** [comment]
Thanks @codekoala! Could you elaborate more about "private networking" and how it would help "to avoid possible bandwidth charges"? Do you mean using private IP addresses for worker nodes?

Thanks!

**Comment by codekoala** [comment]
Yes, that's exactly it! Linode offers private IP addresses that are accessible within each datacenter. If you build a cluster completely in only one datacenter, using these private IP addresses will not count against your bandwidth quota.

![image](https://user-images.githubusercontent.com/48698/27644629-0c5ae5cc-5bf2-11e7-8a41-a16a17961fb4.png)

**Comment by kahkhang** [comment]
Thanks! I'll see if I can work something out this weekend when I find time :)

**Comment by codekoala** [comment]
Sounds great, thanks! Again, it's not a huge priority for me personally right now, so no worries if it takes a while to get to.

**Comment by kahkhang** [comment]
Do you know how to block traffic coming from the public IP address of a linode, while only allowing traffic from the private IP address by any chance? It's something i've been wanting to do for a while, but can't seem to wrap my head around any solutions I've found over the internet (all of them describe solutions to block traffic from an external ip address, which doesn't fit the desired use case), and I can't delete the public ip from a linode. Thanks!

**Comment by codekoala** [comment]
Sorry for my absence... got a bit busy around here. The only thing that really comes to mind with Linode is basic iptables. It becomes a bit more interesting when you start considering the traefik situation though.
