### ISSUE TITLE
Customize storage disk size

### ISSUE THREAD

**Issue by codekoala** [kahkhang/kube-linode#12]
When building a cluster using the smallest available Linode, a storage disk size of 10240MB is great. However, if you're using a larger Linode, only having 10GB available for local storage is a bit of a waste. As far as I can see with a quick grep, it doesn't look like ``STORAGE_DISK_SIZE`` is customizable right now. 

Perhaps there could be an option to set it explicitly, or do a percentage of total disk size per Linode plan, or 
do a fixed size for the CoreOS disk and leave the remainder for local storage.

**Comment by kahkhang** [comment]
I'm working on a PR to customize the number of persistent local disks, as well as the sizes of each
 of them for each node 😉

**Comment by kahkhang** [comment]
Custom local disks are now supported with #13 😄
