### ISSUE TITLE
Worker not deployed

### ISSUE THREAD

**Issue by tuannvm** [kahkhang/kube-linode#16]
Master was successfully span up, but not Workers, it stuck at `Brand New` status somehow. See:
![image](http://i.imgur.com/8Wn5OfK.png)

**Comment by kahkhang** [comment]
Is it due to #17? Can have more information regarding your OS version / the terminal screen when the workers are being deployed?

**Comment by tuannvm** [comment]
Hi, It still happens after https://github.com/kahkhang/kube-linode/issues/17 fix.

My Info:
```
ProductName:	Mac OS X
ProductVersion:	10.12.5
```

Terminal screen:
![image](http://i.imgur.com/CXxeMNM.png)

No error was reported.

**Comment by kahkhang** [comment]
Can I see the disks/boot configuration of your worker linode? What happens if you delete those 2 worker nodes and run kube-linode again?

**Comment by tuannvm** [comment]
I set 10GB for coreos partition.
Same thing happen if I delete & recreate 2 workers.

**Comment by kahkhang** [comment]
Could you click on one the worker nodes in your first screenshot, then screenshot the details of the Linode (i.e. list of disks, list of configurations, jobs)? That will give me more information to diagnose the issue. Thanks!

**Comment by tuannvm** [comment]
See: ![image](http://i.imgur.com/FLiwCoZ.png)

**Comment by kahkhang** [comment]
Hmm this is strange since the initial portion of the script for the worker node is the same as the master one, and it seems like it is not getting any jobs after the initial configuration, which means some portion of the commands failed silently. Could I ask if you are using the default bash version or some other shell (e.g. zsh)? I'll probably need to add a verbose mode for the script so problems like this can be more easily diagnosed. Thanks for reporting the issue!

**Comment by tuannvm** [comment]
I use `fish` shell. As your suggestion, I currently try to run again on `zsh`. Will keep updating.

**Comment by kahkhang** [comment]
Ah ok thanks! I'm not sure of the behavior of fish since I've only used this in bash / zsh currently. I highly suspect it might be failing here: https://github.com/kahkhang/kube-linode/blob/master/utilities.sh#L317. Will investigate more, thanks for the information!

**Comment by tuannvm** [comment]
same issue with `zsh`. I guess it's not shell-specific issue. It would be great if you can add `--verbose` option. In the mean time I'll dig further into the source code when I've time. Thanks for the fast response :)

**Comment by kahkhang** [comment]
Thanks for raising the issue @tuannvm! I think I've found a bug which has been fixed. Please reopen again if the problem is still not solved, or update if it has been solved :)
