### ISSUE TITLE
Add Elasticsearch/Fluentd/Kibana stack

### ISSUE THREAD

**Issue by kahkhang** [kahkhang/kube-linode#33]

**Comment by sundeep-paulraj** [comment]
Hi 
What kind of help are you looking for . i am ready to extend my help, please let me know the requirements .

**Comment by kahkhang** [comment]
Hi @sundeepk1 , sorry for the late reply! It seems that the deploying these manifests would cause the worker node to freeze, so I'm trying to create a minimal ES deployment that would work. I'll close this because I feel that this doesn't fit with the vision of this repo to provide a basic K8S cluster for customization.
