### ISSUE TITLE
Invalid Domain on subdomain

### ISSUE THREAD

**Issue by preeefix** [kahkhang/kube-linode#37]
I use CloudFlare as my primary DNS host, and delegate a subdomain to linode, `cloud.example.com`.

When trying to use the domain on kube-linode, it requires a TLD, although I have the subdomain added into linode.

**Comment by kahkhang** [comment]
My apologies, some work would be needed to support this (quite busy these few days, so will take a while). As a workaround, could you enter `example.com` first, run the provision script `kube-linode.sh` then repoint your A record in `example.com` to your existing IP. Then create separate 'A' records for https://kube.example.com (Kubernetes Dashboard)
https://grafana.example.com (Grafana)
https://alertmanager.example.com (Alert Manager)
https://prometheus.example.com (Prometheus Web UI)
https://traefik.example.com (Traefik Web UI)

to your newly created master node in Cloudflare.

Let me know how this goes, thanks!

**Comment by preeefix** [comment]
Not quite what I was trying to get across. I wanted the ending URLs to be:
https://kube.cloud.example.com,
https://grafana.cloud.example.com,
etc.

**Comment by kahkhang** [comment]
I see, thanks for the clarification! This can definitely be supported, though I'll need some work to support it :) Thanks for the patience!
