### ISSUE TITLE
alertmanager host not found

### ISSUE THREAD

**Issue by c835722** [kahkhang/kube-linode#43]
GIVEN I am an end-user of kube-linode 
WHEN when I put the ingress monitoring host alertmanager into a web browser
THEN its should resolve to the authentication mechinism/initial welcome page.

**Comment by kahkhang** [comment]
Hmm sorry I don't get this issue?

**Comment by c835722** [comment]
I mean that I notice you have a alertmanager host in the confguration.
```
 ~/.usr/local/products/kubernetes/linode/kube-linode   master …  kubectl get ingress --all-namespaces                                        Wed 23 Aug 17:03:33 2017
NAMESPACE     NAME                 HOSTS                                                                    ADDRESS   PORTS     AGE
kube-system   dashboard-ingress    kube.villeroy.xyz,traefik.villeroy.xyz                                             80        2d
monitoring    prometheus-ingress   alertmanager.villeroy.xyz,prometheus.villeroy.xyz,grafana.villeroy.xyz             80        2d
 ~/.usr/local/products/kubernetes/linode/kube-linode   master …     
```
I expressed the issue in BDD format so you might use it as the test should the issue be resolved.
Do let me know if I have missed something obvious.

**Comment by kahkhang** [comment]
It is intended that alertmanager.villeroy.xyz is exposed, is that an issue?

**Comment by c835722** [comment]
It should be exposed but it is not. alertmanager is not working for me built from the master branch instance.

**Comment by kahkhang** [comment]
Can you elaborate more of how it is not working? Is the alertmanager pod running? Pinging alertmanager.villeroy.xyz results in an unknown host, you might want to check your dns settings to see if you've set appropriate A/CNAME records for that. By right this shouldn't happen unless you have some custom settings in your DNS provider.

**Comment by c835722** [comment]
User DNS issue mispelling of alertmamager. Resolved.
