### ISSUE TITLE
Exposing a Service via Traefic

### ISSUE THREAD

**Issue by c835722** [kahkhang/kube-linode#44]
I have a custom app that I have deployed on my kube-linode instance.
Is there any recommendation about how best to add a k8s service to the project instance of Traefic such that it will support current and future project releases?

**Comment by kahkhang** [comment]
What do you mean by project instance? You can define ingresses for your service: https://kubernetes.io/docs/concepts/services-networking/ingress/

**Comment by c835722** [comment]
I mean I want to expose my service through Treafic(Reverse Proxy) to pickup the value of its capabilities above and beyond k8s and am seeking whether you have a recommended way to do this such that it will work now and with whatever future project plans there is. That is, as a user I want to be able to deploy my service on top of the facilities provided by the project (kube-linode) in a fashion that wont be fragile and seek suggestion/guidance if it exists.

**Comment by kahkhang** [comment]
Hmm the standard way to expose a service in k8s is through an ingress: https://kubernetes.io/docs/concepts/services-networking/ingress/. This ingress is agnostic to any ingress controller, and thus should work for any reverse proxies (eg. nginx)
