### ISSUE TITLE
Quick question (DNS)

### ISSUE THREAD

**Issue by itsJess1ca** [kahkhang/kube-linode#49]
Hi, This looks amazing and I'm hoping I can use it.
I just had one question and that was, is it required to use Linode's DNS with this? My team uses Route53 for our DNS management currently and I can't switch that over to Linode.

**Comment by kahkhang** [comment]
Thanks for the kind words! Route53 works too, just point the A record (example.com) to your master IP, and create a wildcard CNAME domain (*.example.com) to your master IP as well :)

**Comment by itsJess1ca** [comment]
Perfect, thank you. 
This should make my life a bit easier going forward ;)
