### ISSUE TITLE
Teardown?

### ISSUE THREAD

**Issue by daniellacosse** [kahkhang/kube-linode#56]
Hey - working on a personal development pipeline and I have this E2E test script that tears everything down at the end. Would love to do the same for your script - would anything need to be cleaned up apart from the master/worker linode instances?

**Comment by kahkhang** [comment]
If the entire cluster is to be deleted, I guess deleting all the linode master/worker instances would suffice. You might also want to delete the "cluster/" folder, which contains all the manifests/certs for the particular cluster :)

**Comment by kahkhang** [comment]
Fixed with #64
