### ISSUE TITLE
Possible to get bare bones version?

### ISSUE THREAD

**Issue by orbitalmedia** [kahkhang/kube-linode#58]
Real Nice project - would be great to have with this just a bare cluster ( no traefik, rook, prometheus etc )
Cheers,

**Comment by kahkhang** [comment]
Hi, thanks for the suggestion! Being able to select services for deployment is in the pipeline, but for now if you want a quick solution you can comment out the manifests here https://github.com/kahkhang/kube-linode/blob/master/linode-utilities.sh#L300 for services which you do not want.

**Comment by daniellacosse** [comment]
👉 https://github.com/kahkhang/kube-linode/pull/62 🎊
