### ISSUE TITLE
No DNS entries for kube.domain.com or traefik.domain.com

### ISSUE THREAD

**Issue by codekoala** [kahkhang/kube-linode#7]
Per the readme, I expected to find DNS entries for both ``kube.domain.com`` and ``traefik.domain.com``, but it would seem that is not actually the case.

![image](https://user-images.githubusercontent.com/48698/27638367-032d7a7a-5be1-11e7-9054-5fb4a92d75eb.png)

**Comment by kahkhang** [comment]
Ah I actually created a wildcard CNAME record so all aliases *.example.com will point to the master node IP, so additional ingress routes can be placed. Is there an advantage in creating A records compared to just a wildcard CNAME record?

**Comment by codekoala** [comment]
Ah, fair point on the CNAME record. I guess I simply didn't give it enough time for the changes to replicate!

I don't think there would be any particular benefit to creating individual A records in this case.
