### ISSUE TITLE
Document DNS record destruction

### ISSUE THREAD

**Issue by codekoala** [kahkhang/kube-linode#8]
When I first ran ``kube-linode``, I was a bit surprised to see that it destroyed DNS records that were previously configured for Google Apps for my domain. It would be helpful to point this out in the README, perhaps also with a prompt at runtime that confirms the user is ok with removing any existing DNS records.

**Comment by kahkhang** [comment]
My apologies, I did this so that the script could be run multiple times without creating additional A/AAA and CNAME records. I'll make the script smarter in adding specific A/CNAME records only if that particular record is not found
