### ISSUE TITLE
Make email address optional

### ISSUE THREAD

**Issue by thefinn93** [kahkhang/kube-linode#83]
ACME registration doesn't require an email, so the user shouldn't be force to provide one. Allowing them to enter one is fine, but maybe say "(optional)" after the prompt. Not sure if traefik will allow this, but I dont see any reason why it wouldn't.

**Comment by kahkhang** [comment]
Sorry I must admit I don't really know the ACME protocol in detail, but it seems like Traefik requires that an email be set in order for the certificates to be auto-renewed (https://docs.traefik.io/configuration/acme/). I'll close this for now (for housekeeping the number of open issues), but feel free to open this issue if there is a way for me to get Traefik to auto-renew the certs without providing an email. Thanks!
