### ISSUE TITLE
Prompt before deleting any files on teardown

### ISSUE THREAD

**Issue by thefinn93** [kahkhang/kube-linode#84]
I was trying to figure out why my `settings.env` file kept getting deleted, turns out `./kube-linode.sh teardown` ends with:

```bash
rm -rf cluster
rm -rf $HOME/.kube
rm auth
rm settings.env
```
which is very unexpected, especially deleting stuff from outside the `kube-linode` directory (such as `$HOME/.kube`). I propose prompting the user, and clearly explaining all of the files that will be deleted, maybe giving the option to preserve `settings.env` and/or anything that isn't in the `kube-linode` directory.

**Comment by displague** [comment]
I would also suggest that `teardown` should report the Linodes that it will be removing, with a prompt at the end.

The README says `teardown` will remove everything -- that could be explained better too.

**Comment by kahkhang** [comment]
Thanks for the input! Sorry I didnt realise that this command had unexpected behaviors. I've updated this command (now renamed `./kubectl destroy` to emphasize the destructive nature of the command), and the command will now report the linodes that it is removing (with corresponding links to that linode's dashboard page), and it will also prompt another two times, one to prompt for DNS record deletion, and another to delete existing configuration. 

Feel free to let me know if there's other stuff that can be made better / any pain points. Thanks!
