### ISSUE TITLE
Add a new ssh key

### ISSUE THREAD

**Issue by raducrisan1** [kahkhang/kube-linode#86]
Hi,

I installed a cluster having one master and one worker. How can I add a new authorized ssh key on any of the nodes?I tried to ssh and it asked for password. I used the same machine as when I created the cluster.

**Comment by raducrisan1** [comment]
Found it. I had to use the user "core". 

`ssh core@linodeserverip`

**Comment by kahkhang** [comment]
Yep core is the username :)
