### ISSUE TITLE
Hangs at "Installing CoreOS" with no PRIVATE_IP for legacy accounts

### ISSUE THREAD

**Issue by evanp** [kahkhang/kube-linode#87]
I'm trying to get a first install, but the installation stops at "Installing CoreOS". If I log into the master server, I see the shell script but not the "ct" file, and gawk is not installed. This line:

> PRIVATE_IP=$(ip addr show eth0 | grep "inet\b" | grep "/17" | awk '{print $2}' | cut -d/ -f1)

...if I run it on the server, doesn't generate any value for PRIVATE_IP. If I run `ip addr show eth0`, it doesn't output a `/17` address.

**Comment by evanp** [comment]
I wondered if there was something on my account that was not setting up a private IP. The "Network Helper" was disabled in Account Settings, which apparently is the default for old accounts. I've enabled it, and I'm re-running the install to see if it helps.

**Comment by evanp** [comment]
That did it! Maybe there should be a check for the PRIVATE_IP value before continuing?

**Comment by kahkhang** [comment]
Thanks for the update! Unfortunately I wasn't aware of this behavior :( Yea maybe something can be done to validate the private IP / network helper to solve this.
