### ISSUE TITLE
Guide for arch linux installation - install.sh missing

### ISSUE THREAD

**Issue by itsJess1ca** [kahkhang/kube-linode#91]
I started following the guide for arch linux referenced at https://github.com/kahkhang/kube-linode/issues/4#issuecomment-311601422

However the link for the following step is now a 404. Any advice for getting past this? :)
Is it still needed?
```
#To install
curl -s https://raw.githubusercontent.com/kahkhang/kube-linode/master/install.sh | bash
```

**Comment by kahkhang** [comment]
My apologies this isn't needed anymore, if you just run the current instruction, I.e. `./kube-linode.sh create` after cloning this repository it should work fine :)

I should really update the instructions sometime, this was a couple of months back before I made extensive changes.

**Comment by itsJess1ca** [comment]
Ah that seems to be doing the trick (though there are some visual glitches due to no spinner)

I was also missing the package `procps` so had to rectify that :)

Thank you for a great tool!

EDIT: Just wanted to add after it finished building everything was a success :+1: Thanks again
