### ISSUE TITLE
Old kubernetes version is deployed

### ISSUE THREAD

**Issue by anjmao** [kahkhang/kube-linode#92]
I installed kubernetes cluster few days ago and I noticed that after creating private docker images registry secret, It was using old docker format

```
kubectl get secret regcred --output=yaml
```
```yaml
apiVersion: v1
data:
  .dockercfg: <secret>
kind: Secret
metadata:
  creationTimestamp: 2018-03-24T17:35:46Z
  name: regcred
  namespace: default
  resourceVersion: "531948"
  selfLink: /api/v1/namespaces/default/secrets/regcred
  uid: <uid>
type: kubernetes.io/dockercfg
```
In kubernetes 1.9 it uses type of `type: kubernetes.io/dockerconfigjson`

Here is kubernetes version that I see

```json
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:05:18Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

https://github.com/kahkhang/kube-linode/blob/master/manifests/container-linux/master-config.yaml#L55 Here default BOOTKUBE_VERSION is 0.9.3 which includes kuernetes 1.8

**Comment by kahkhang** [comment]
Thanks for the catch @anjmao! I might have bumped the hyperkube version too early before bootkube upgraded their hyperkube version :(
