### ISSUE TITLE
Issue with rook provisioning

### ISSUE THREAD

**Issue by IngCr3at1on** [kahkhang/kube-linode#95]
Tried to setup a cluster last night and left all options enabled.
The process stalled during the worker node provisioning and did not progress. After disabling rook and starting over the process worked fine.

---

I decided to try to apply the rook config manually:

```
kubectl apply -f manifests/rook/rook-operator.yaml
kubectl apply -f manifests/rook/rook-cluster.yaml
```
before I can run the third command the second errors with:
```
namespace "rook" configured
error: unable to recognize "rook-cluster.yaml": no matches for kind "Cluster" in version "rook.io/v1alpha1"
```
everything I read suggests that's because the operator is not ready but again after several hours this is still not able to be applied and so far as I can tell the operator is running apart from the following log entry being repeated (which to me seems implied by the above):

```
E0505 01:27:19.102629       5 reflector.go:205] github.com/rook/rook/vendor/github.com/rook/operator-kit/watcher.go:76: Failed to list *v1alpha1.Cluster: the server could not find the requested resource (get clusters.rook.io
```

**Comment by nbiles** [comment]
I am getting the same issue :(

Any luck figuring it out?

```
error: unable to recognize "manifests/rook/rook-cluster.yaml": no matches for rook.io/, Kind=Cluster
```

**Comment by IngCr3at1on** [comment]
@nbiles not as of yet I was hoping someone else would have some sort of idea. It's about the only thing not working on my cluster right :(

**Comment by nbiles** [comment]
I'm still looking into it. This is a rather urgent issue for me. I have a demo on Monday and I have more work to do and need rook working.

**Comment by IngCr3at1on** [comment]
good luck, let me know if you find something, my linode cluster is just for fiddling luckily lol

**Comment by nbiles** [comment]
well, I was able to [install rook operator using helm](https://rook.io/docs/rook/master/helm-operator.html) then running the manifests:

```
kubctl apply -f manifests/rook/rook-cluster.yaml
kubctl apply -f manifests/rook/rook-storageclass.yaml
kubctl apply -f manifests/rook/rook-tools.yaml
```

BUT I'm not sure if this is working. Everything looks good except when I try to mount a pvc:

```
Unable to mount volumes for pod ... : timeout expired waiting for volumes to attach/mount for pod " ... ". list of unattached/unmounted volumes=[mysql-storage]
```

Not sure what is going on because this helm chart (deployment) was working on a cluster I had up last week.

Have you seen this?
