### ISSUE TITLE
No Config Profile provided

### ISSUE THREAD

**Issue by MarkMangoba** [kahkhang/kube-linode#98]
When trying to run ./kube-linode.sh create, the process fails silently on:
- Installing CoreOS (might take a while)
- In Linode Manager:  Linode cannot boot due to:  "No Configuration Profile Detected"

Therefore, it cannot continue the process.

**Comment by kahkhang** [comment]
Thanks for highlighting the issue @MarkMangoba! Sigh seems like Linode recently increased their minimum disk size for the install OS

```
{"ACTION":"linode.disk.createFromDistribution","DATA":{},"ERRORARRAY":[{"ERRORMESSAGE":"Distribution requires a minimum size of 1300MB","ERRORCODE":8}]}
```

Will do a fix now.
